(function () {
    // Purify Embedded - v1.0.1 - GPL3
    // (c) themirrazzkun 2025+
    var purify={icra:{decode:function(set,index){var pairs=set.split(" ");var alpha='abcdefghijklmnopq';var table={c:['unmoderated','moderated'],l:['explicit','moderate','mild'],n:['erections','maleGenitals','femaleGenitals','breasts','butt','explicit','implied','touching','kissing'],v:['rape','blood','bloodAnimal','bloodFantasy','killing','killingAnimal','killingFantasy','violence','animalCruelty','fantasyViolence','vandalism'],o:['tobacco','alcohol','drugs','gambling','weapons','harm','badExample','disturbing']};var prefixs={c:'chat',l:'language',n:'nudity',v:'violence',o:'misc'};var results={chat:{unmoderated:!1,moderated:!1,none:!1},language:{explicit:!1,moderate:!1,mild:!1,none:!1},nudity:{erections:!1,maleGenitals:!1,femaleGenitals:!1,breasts:!1,butt:!1,explicit:!1,implied:!1,touching:!1,kissing:!1,artistic:!1,educational:!1,medical:!1},violence:{rape:!1,blood:!1,bloodAnimal:!1,bloodFantasy:!1,killing:!1,killingAnimal:!1,killingFantasy:!1,violence:!1,fantasyViolence:!1,animalCruelty:!1,vandalism:!1,none:!1,artistic:!1,educational:!1,medical:!1,sports:!1},misc:{tobacco:!1,alcohol:!1,drugs:!1,gambling:!1,weapons:!1,harm:!1,badExample:!1,disturbing:!1,none:!1}};for(var i=0;i<pairs.length;i+=2){var key=pairs[i];var value=pairs[i+1];if(!prefixs[key.charAt(0)]){throw TypeError("Invalid ICRA key "+key+" at line 1, column "+index)}
if('zrsti'.indexOf(key.charAt(1))<0){if(!table[key.charAt(0)][alpha.indexOf(key.charAt(1))]){throw TypeError("Invalid ICRA key "+key+" at line 1, column "+index)}}
if(value!=='1'){throw TypeError("ICRA value must be 1 at line 1, column "+index)}
if(key.charAt(1)==='z'){results[prefixs[key.charAt(0)]].none=!0}else if(key.charAt(1)==='r'){results[prefixs[key.charAt(0)]].artistic=!0}else if(key.charAt(1)==='s'){results[prefixs[key.charAt(0)]].educational=!0}else if(key.charAt(1)==='t'){results[prefixs[key.charAt(0)]].medical=!0}else if(key.charAt(1)==='u'){results[prefixs[key.charAt(0)]].sports=!0}else{results[prefixs[key.charAt(0)]][table[key.charAt(0)][alpha.indexOf(key.charAt(1))]]=!0}}
return results}},rsac:{decode:function(set,index){var pairs=set.split(' ');var levels={nudity:0,violence:0,language:0,sex:0};var table={n:'nudity',v:'violence',l:'language',s:'sex'};for(var i=0;i<pairs.length;i+=2){if(!table[pairs[i]]){throw new ReferenceError('Unknown key')}
if(isNaN(pairs[i+1])){throw new TypeError('Not a number')}
if(Math.floor(pairs[i+1])!=pairs[i+1]){throw new TypeError('Not an integer')}
if(pairs[i+1]<0){throw new TypeError('Must be zero or greater')}
if(pairs[i+1]>4){throw new TypeError('Must be four or lesser')}
levels[table[pairs[i]]]=Number(pairs[i+1])}
return levels}},parse:function(rating){var lexed=purify.lexar(rating);var ratings=[];var rating={};var ratingURL='';var comment='';var genLevel=-1;var nextEqualsComment=!1;for(var i=0;i<lexed.length;i++){if(lexed[i].type==='BOOLEAN'){if(lexed[i].value==='true'){genLevel=1}else{genLevel=0}}else if(lexed[i].type==='KEYWORD'){if(lexed[i].value==='comment'){nextEqualsComment=!0}}else if(lexed[i].type==='STRING_LITERAL'){if(!ratingURL){ratingURL=lexed[i].value}
if(nextEqualsComment){comment=lexed[i].value}}else if(lexed[i].type==='RATING'){rating={namespace:ratingURL,data:lexed[i].value,comment:comment,gen:genLevel};try{if(ratingURL==='http://www.icra.org/ratingsv02.html'){rating.rating=this.icra.decode(lexed[i].value,lexed[i].end-lexed[i].value.length)}else if(ratingURL==='http://www.rsac.org/ratingsv01.html'){rating.rating=this.rsac.decode(lexed[i].value,lexed[i].end-lexed[i].value.length)}}catch(error){rating.parsingError=error}
ratings.push(rating);comment='';genLevel=-1;ratingURL=''}}
return ratings},lexar:function(rating){if(!rating.charAt(0)){return[]}
if(rating.charAt(0)!=='('){throw new SyntaxError("Unexpected token \""+rating.charAt(0)+"\" at line 1, column 1")}
var out=[];var bc='';var c='';var cp='';var cpp='';var inHeader=!0;var isBeginning=!1;var inURL=!1;var inComment=!1;var isInGen=!1;var isInFor=!1;var isRightBeforeGen=!1;var isRightBeforeComment=!1;var isRightBeforeRating=!1;var isInRating=!1;var isRightBeforeFor=!1;var didFor=!1;var didURL=!1;var didComment=!1;var didGen=!1;var tok='';var last='whitespace';var ESCAPES={'t':'\t','n':'\n','r':'\r'};for(var i=1;i<rating.length;i++){bc=rating.charAt(i-1)||'';c=rating.charAt(i);cp=rating.charAt(i+1)||'';cpp=rating.charAt(i+2)||'';if(inComment||inURL||isInFor){if(c==='\\'){if(!cp){throw new SyntaxError("Unexpected EOL at line 1, column "+(i+1))}else{tok+=ESCAPES[cp]||cp;i+=1}}else if(c==='"'){if(!cp){throw new SyntaxError("Unexpected EOL at line 1, column "+(i+1))}else if(cp!==' '&&cp!=='
'){throw new SyntaxError("Unexpected token \""+cp+"\" at line 1, column "+(i+1))}else{if(inComment){didComment=!0}else if(inURL){didURL=!0}else if(isInFor){didFor=!0}
inComment=inURL=isInFor=!1;out.push({type:"STRING_LITERAL",value:tok,end:i});tok="";out.push({type:"STRING_TERMINATOR",value:'\"',end:i+1});last='string'}}else{tok+=c}}else if(isInRating){if(c===')'){if(!cp){throw new SyntaxError("Unexpected EOL at line 1, column "+(i+1))}else if(cp!==' '&&cp!=='
'){if(cp===')'){if(cpp){throw new SyntaxError("Unexpected token \""+cpp+"\" at line 1, column "+(i+2))}}else{throw new SyntaxError("Unexpected token \""+cp+"\" at line 1, column "+(i+1))}}
out.push({type:"RATING",value:tok,end:i});tok='';out.push({type:"RATING_TERMINATOR",value:')',end:i+1});isBeginning=!0;inURL=!1;inComment=!1;isInGen=!1;isInFor=!1;isRightBeforeGen=!1;isRightBeforeComment=!1;isRightBeforeRating=!1;isInRating=!1;isRightBeforeFor=!1;didFor=!1;didURL=!1;didComment=!1;didGen=!1}else{tok+=c}}else{if(c===' '){if(tok){if(isInGen){if(tok!=='true'&&tok!=='false'){throw new TypeError("Expected boolean literal, but got unknown value at line 1, column "+(i-tok.length))}
didGen=!0;isInGen=!1;isRightBeforeGen=!1;out.push({type:"BOOLEAN",value:tok,end:i})}else if(inHeader){if(tok==='pics-1.1'||tok==='pics-1.0'){inHeader=!1;isBeginning=!0}else if(tok.indexOf('pics-')===0){throw new SyntaxError("Invalid header version at line 1, column "+(i-tok.length))}else{throw new SyntaxError("Missing header at line 1, column "+(i-tok.length))}}else if(isRightBeforeComment||isBeginning){throw new TypeError("Expected string literal, but got unknown value at line 1, column "+(i-tok.length))}else if(isRightBeforeRating){throw new TypeError("Expected rating literal, but got unknown value at line 1, column "+(i-tok.length))}else if(isRightBeforeGen){if(tok!=='gen'&&tok!=='generic'){throw new SyntaxError("Expected keyword \"gen\", but got invalid token at line 1, column "+(i-tok.length))}
isInGen=!0;out.push({type:"KEYWORD",value:tok,end:i})}else{if(tok==='l'||tok==='labels'){isRightBeforeGen=!0;out.push({type:"KEYWORD",value:tok,end:i})}else if(tok==='for'){if(!didGen){throw new SyntaxError("Attempted to declare the \"for\" field when the \"gen\" field has not yet been declared at line 1, column "+(i-tok.length))}
isRightBeforeFor=!0;out.push({type:"KEYWORD",value:tok,end:i})}else if(tok==='comment'){isRightBeforeComment=!0;out.push({type:"KEYWORD",value:tok,end:i})}else if(tok==='r'||tok==='ratings'){if(didGen&&!didFor){throw new SyntaxError("Attempted to declare the \"r\" field when the \"for\" field has not yet been declared at line 1, column "+(i-tok.length))}
isRightBeforeRating=!0;out.push({type:"KEYWORD",value:tok,end:i})}else{throw new SyntaxError("Unexpected token \""+tok+"\" at line 1, column "+(i-tok.length))}}}
tok=''}else if(c==='\"'){if(isBeginning){isBeginning=!1;inURL=!0;out.push({type:"STRING_START",value:'\"',end:i+1});tok=''}else if(isRightBeforeComment){isRightBeforeComment=!1;if(didComment){throw new SyntaxError("Attempted to declare a comment after comment had already been declared at line 1, column "+i)}
inComment=!0;out.push({type:"STRING_START",value:'\"',end:i+1});tok=''}else if(isRightBeforeFor){isRightBeforeFor=!1;if(didFor){throw new SyntaxError("Attempted to declare a for statement after for statement had already been declared at line 1, column "+i)}
isInFor=!0;out.push({type:"STRING_START",value:'\"',end:i+1});tok=''}else{throw new SyntaxError("Unexpected string literal at line 1, column "+i)}}else if(c==='('){if(isRightBeforeRating){isInRating=!0;out.push({type:"RATING_START",value:'(',end:i+1});tok=''}else{throw new SyntaxError("Unexpected rating literal at line 1, column "+i)}}else if(c===')'){if(cp){throw new SyntaxError("Unexpected EOL charcater before end of line at line 1, column "+i)}
out.push({type:"LINE_TERMINATOR",value:')',end:i+1})}else{tok+=c}}}
return out}}
    return purify;
})();
